/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopet;

import Conexion.ConectaBD;
import Modelos.ModeloMascota;
import Modelos.ModeloUsuario;
import Objetos.User;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cmejuto
 */
public class Usuario extends javax.swing.JFrame {

    Principal principal;
    String user;
    Connection c;
    User usuario;
    ModeloMascota mm;

    //contructor pasándole usuario
    public Usuario(String user, Principal principal) throws SQLException {
        this.principal = principal; 
        this.user = user;
        mm = new ModeloMascota(5); //ojo!! instanciamos el objeto dentro del constructor mandando el número de columnas de la tabla
        //System.out.println(user); //comprobamos si recibe el usuario
        initComponents();
        setLocationRelativeTo(null); //para centrar la ventana

        c = new ConectaBD().getConn();

        recuperaRegistro();
    }

//    //constructor pasándole principal
//    public Usuario(Principal principal) throws SQLException {
//        this.principal = principal; 
//        initComponents();
//        setLocationRelativeTo(null); //para centrar la ventana
//        
//    }
    public void recuperaRegistro() throws SQLException {
        Statement stm = c.createStatement();
        ResultSet rs = stm.executeQuery("select * from usuario where user = '" + user + "'");
        while (rs.next()) {
            usuario = new User(rs.getInt(1), rs.getString(2), rs.getInt(3),
                    rs.getString(4), rs.getString(5), rs.getString(6),
                    rs.getString(7), rs.getString(8));
            //System.out.println(usuario.toString());
        }
        tprovincia.setText(usuario.getProvincia());
        tnombre.setText(usuario.getUnombre());
        tdirecc.setText(usuario.getDireccion());
        ttlf.setText(String.valueOf(usuario.getTlf()));
        tmail.setText(usuario.getMail());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        beditar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        bactualizar = new javax.swing.JButton();
        unombre = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        tmail = new javax.swing.JTextField();
        ttlf = new javax.swing.JTextField();
        tprovincia = new javax.swing.JTextField();
        tdirecc = new javax.swing.JTextField();
        tnombre = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        provincia = new javax.swing.JLabel();
        tlf = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableMascota = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        jButton4 = new javax.swing.JButton();

        setTitle("Usario");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de usuario"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        beditar.setText("Editar datos");
        beditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarActionPerformed(evt);
            }
        });
        jPanel4.add(beditar);
        jPanel4.add(filler2);

        bactualizar.setText("Actualizar");
        bactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactualizarActionPerformed(evt);
            }
        });
        jPanel4.add(bactualizar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jPanel4, gridBagConstraints);

        unombre.setText("Nombre y apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(unombre, gridBagConstraints);

        mail.setText("Correo electronico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        jPanel1.add(mail, gridBagConstraints);

        tmail.setEnabled(false);
        tmail.setMinimumSize(new java.awt.Dimension(60, 20));
        tmail.setPreferredSize(new java.awt.Dimension(120, 20));
        tmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(tmail, gridBagConstraints);

        ttlf.setEnabled(false);
        ttlf.setMinimumSize(new java.awt.Dimension(60, 20));
        ttlf.setPreferredSize(new java.awt.Dimension(120, 20));
        ttlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(ttlf, gridBagConstraints);

        tprovincia.setEnabled(false);
        tprovincia.setMinimumSize(new java.awt.Dimension(60, 20));
        tprovincia.setPreferredSize(new java.awt.Dimension(120, 20));
        tprovincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tprovinciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(tprovincia, gridBagConstraints);

        tdirecc.setEnabled(false);
        tdirecc.setMinimumSize(new java.awt.Dimension(60, 20));
        tdirecc.setPreferredSize(new java.awt.Dimension(120, 20));
        tdirecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdireccActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(tdirecc, gridBagConstraints);

        tnombre.setEnabled(false);
        tnombre.setMinimumSize(new java.awt.Dimension(60, 20));
        tnombre.setPreferredSize(new java.awt.Dimension(260, 20));
        tnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(tnombre, gridBagConstraints);

        direccion.setText("Dirección completa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(direccion, gridBagConstraints);

        provincia.setText("Provincia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(provincia, gridBagConstraints);

        tlf.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(tlf, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de mascotas"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane6.setPreferredSize(new java.awt.Dimension(384, 150));

        jTableMascota.setModel(mm);
        jScrollPane6.setViewportView(jTableMascota);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane6, gridBagConstraints);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setText("Añadir mascota");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jPanel3.add(filler1);

        jButton4.setText("Borrar mascota");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarActionPerformed
        // habilitamos los campos de texto
        tprovincia.setEnabled(true);
        tnombre.setEnabled(true);
        tdirecc.setEnabled(true);
        ttlf.setEnabled(true);
        tmail.setEnabled(true);
    }//GEN-LAST:event_beditarActionPerformed

    private void bactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactualizarActionPerformed
        try {
            // Actualizamos los datos del usuario
            Statement s = c.createStatement();
            s.executeUpdate("update usuario set unombre = '" + tnombre.getText() + "', "
                    + "tlf = " + ttlf.getText() + ",mail = '" + tmail.getText() + "', "
                    + "direccion = '" + tdirecc.getText() + "', "
                    + "provincia = '" + tprovincia.getText() + "' where user = '" + user + "'");

            //lanzamos un mensaje de respuesta
            JOptionPane.showMessageDialog(null, "Los campos han sido actualizados", "Actualización de datos", JOptionPane.INFORMATION_MESSAGE);
            //deshabilitamos los campos de nuevo
            tprovincia.setEnabled(false);
            tnombre.setEnabled(false);
            tdirecc.setEnabled(false);
            ttlf.setEnabled(false);
            tmail.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bactualizarActionPerformed

    private void tprovinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tprovinciaActionPerformed
        //campo provincia

    }//GEN-LAST:event_tprovinciaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //borramos mascota
        //tenemos un objeto jTableMascota que es el que contiene el modelo. 
        int codigoEliminar = (int) mm.getValueAt(jTableMascota.getSelectedRow(), 0);//en el modelo cogemos el valor de la fila activa de la tabla, en la posición 0 que es el código
        //llamamos al método del modelo que elimina una línea y actualiza la bd
        mm.eliminar(codigoEliminar);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            //activamos la pantalla de añadir mascota
            Mascota mascota = new Mascota (user, this);
            System.out.println("mandando " + user);
            mascota.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnombreActionPerformed

    }//GEN-LAST:event_tnombreActionPerformed

    private void tdireccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdireccActionPerformed

    }//GEN-LAST:event_tdireccActionPerformed

    private void ttlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlfActionPerformed

    }//GEN-LAST:event_ttlfActionPerformed

    private void tmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmailActionPerformed

    }//GEN-LAST:event_tmailActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new Usuario().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactualizar;
    private javax.swing.JButton beditar;
    private javax.swing.JLabel direccion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableMascota;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel provincia;
    private javax.swing.JTextField tdirecc;
    private javax.swing.JLabel tlf;
    private javax.swing.JTextField tmail;
    private javax.swing.JTextField tnombre;
    private javax.swing.JTextField tprovincia;
    private javax.swing.JTextField ttlf;
    private javax.swing.JLabel unombre;
    // End of variables declaration//GEN-END:variables
}
